---
title: "Workshop Outline"
date: "Updated: `r format(Sys.Date())`"
output: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Module 1: Data Wrangling

  - (5 min): Basic overview of RStudio layout and use
    - mention global settings, how to change layout
    - show how to turn off restore workspace (.RData) as default, and stop asking to save workspace (explain "clean" start")
  - (5-10 min): How to read in data! (csv)
    - what are functions/libraries? How to use a function?
    - read in a csv with `read.csv`
    - `View` the object, show how to filter/search in RStudio
  - (5-10 min): variable storage/data in R
    - demo of variable storage: assigning a new object (i.e., col from existing data frame), using `$` to access parts of an object)
    - basic overview of data classes: assigning a list of numbers, characters, mixed, with NA or missing values
  - (10 min): Intro to `dplyr`
    - manipulating data with dplyr (simple filter, rename column, add a column)
    - Show both dplyr and simple base code to do the same bits.
    - Introduce the pipe %>%
  - (5 min): Use Function!
    - Describe functions and groups of functions as a library (spells in a book)
    - use a package and a function to read in some data from USGS (get flow data for a gage)
    - use this data for "challenge" to manipulate and clean (doing only the same commands covered above)
  - (5 min): Base plot
    - make a simple plot of river flow or ppt using baseplot with both datasets
      - advanced: how to save a plot!

## Module 2: Make a Map from A Spreadsheet

### 2-1 read_xls

  - (10 min): Read data from excel spreadsheet
    - Reiterate tidy data, and why it matters (even for spreadsheets!)
      - add link to messy spreadsheets carpentries lesson
      - read in `Tab1` which is messy and breaks things
      - then read in `Tab2` which is "tidied" and doesn't break (use latlon.csv)
      - Challenge/Practice: read `Tab3` which is just a copy of the cscidat.csv
      - save as Rdata/RDS (describe diff)

### 2-2 Joins

  - (10 min): **Join** Data
      - Join the sitecodes from `latlons` with the `cscidat`
      - show figure of joins from allison, briefly talk about inner/outer/anti/left joins
      - save as Rdata file
      - Shovel: mention the tidylog package and show demo of messages printed

### sf package

  - (10 min): Quick overview of **sf**
    - explain the 'sf' package and show sf website (so many options!)
    - make data (from above) spatial (X/Y) with `{sf}`
    - read in a shapefile

### Making Maps!

  - (5 min): Make a map with `{mapview}`!
  - (10 min): Introduce `ggplot2::geom_sf`
    - gently (re)introduce structure of ggplot
    - use data to show `geom_sf` and make a simple map with ggplot
    - shovel: add reference on ggspatial/tmap (adding scale bar and north arrow)
    - reference mapping website, Robin Lovelace's site

## Module 3

- load .gpx files with sf
- show how to download river flow lines with NHDtools
- show how to download gage data for given river
- do some spatial operation (buffer, intersection, nearest?)
- make a map with tmap? (advanced challenge)
- save out to different spatial format (gpkg example, make sure state it works with ArcGIS)